package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/Aznyi/HarborMaster/internal/domain"
)

// PolicyRepository owns persistence for policy definitions, violations, and
// evaluations.
//
// # Bounded reads
//
// Every list is paginated, every sort field comes from an allowlist, and the
// summary is a handful of aggregate queries rather than a list the caller
// counts. The summary is what a dashboard polls, so it is the one that must not
// become O(violations).
//
// # No N+1
//
// The engine loads every active policy ONCE per sweep through ActivePolicies
// and applies that slice to each container. Nothing in the evaluation path
// queries per container except the single reconcile transaction that writes its
// result.
type PolicyRepository struct {
	db *sql.DB
}

// ErrPolicyNameTaken reports a duplicate policy name.
//
// Names are not identifiers -- the immutable policy id is -- but two policies
// called "Production baseline" make a violation list unreadable, so the name is
// unique among policies that are not archived.
var ErrPolicyNameTaken = errors.New("a policy with that name already exists")

// policySortFields is the allowlist of sortable policy columns.
//
// An allowlist rather than validation-by-rejection: the value becomes part of
// the SQL text, so the only safe design is one where caller input SELECTS from
// a fixed set of literals rather than contributing to it.
var policySortFields = map[string]string{
	"name":      "name",
	"severity":  policySeverityRankSQL,
	"createdAt": "created_at",
	"updatedAt": "updated_at",
	"rules":     "rule_count",
	"id":        "id",
}

// policyViolationSortFields is the allowlist for the violation list.
var policyViolationSortFields = map[string]string{
	"detectedAt": "detected_at",
	"lastSeenAt": "last_seen_at",
	"id":         "id",
	"container":  "container_name",
	"policy":     "policy_name",
	"rule":       "rule_type",
	"status":     "status",
	"severity":   policySeverityRankSQL,
}

// policySeverityRankSQL orders by how much a row matters rather than by the
// spelling of its severity. Built from literals only.
const policySeverityRankSQL = `CASE severity ` +
	`WHEN 'critical' THEN 4 ` +
	`WHEN 'high' THEN 3 ` +
	`WHEN 'medium' THEN 2 ` +
	`WHEN 'low' THEN 1 ` +
	`ELSE 0 END`

// ValidPolicySortField reports whether field names a sortable policy column.
func ValidPolicySortField(field string) bool {
	_, ok := policySortFields[field]
	return ok
}

// ValidPolicyViolationSortField reports whether field names a sortable
// violation column.
func ValidPolicyViolationSortField(field string) bool {
	_, ok := policyViolationSortFields[field]
	return ok
}

// ------------------------------------------------------------ definitions --

// PolicyFilter narrows a policy listing.
type PolicyFilter struct {
	// EnabledOnly restricts to policies that participate in evaluation.
	EnabledOnly bool
	// IncludeArchived includes withdrawn policies. Excluded by default: an
	// archived policy is history, and a list dominated by history buries the
	// rules actually in force.
	IncludeArchived bool
	Search          string

	Sort      string
	Ascending bool
	Page      Page
}

const selectPolicyColumns = `
	SELECT id, policy_id, name, description, severity,
	       enabled, archived, archived_at, rules_json, created_at, updated_at
	FROM policy_definitions`

// CreatePolicy stores a new definition.
//
// The policy id is generated by the caller (domain.NewPolicyID) and is never
// derived from caller input, so a caller cannot choose or collide with one.
func (r *PolicyRepository) CreatePolicy(
	ctx context.Context,
	policy domain.PolicyDefinition,
	now time.Time,
) (domain.PolicyDefinition, error) {
	rules, err := encodePolicyRules(policy.Rules)
	if err != nil {
		return domain.PolicyDefinition{}, err
	}
	stamp := formatTime(now.UTC())

	taken, err := r.nameTaken(ctx, policy.Name, "")
	if err != nil {
		return domain.PolicyDefinition{}, err
	}
	if taken {
		return domain.PolicyDefinition{}, ErrPolicyNameTaken
	}

	enabled := 0
	if policy.Enabled {
		enabled = 1
	}

	result, err := r.db.ExecContext(ctx, `
		INSERT INTO policy_definitions
			(policy_id, name, description, severity, enabled, archived,
			 rules_json, rule_count, created_at, updated_at)
		VALUES (?, ?, ?, ?, ?, 0, ?, ?, ?, ?)`,
		policy.PolicyID, policy.Name, policy.Description, string(policy.Severity),
		enabled, rules, len(policy.Rules), stamp, stamp)
	if err != nil {
		return domain.PolicyDefinition{}, fmt.Errorf("insert policy: %w", AsError(err))
	}

	// Reported for the returned row only; the insert has already succeeded.
	id, _ := result.LastInsertId()
	policy.ID = id
	policy.Archived = false
	policy.CreatedAt = now.UTC()
	policy.UpdatedAt = now.UTC()
	return policy, nil
}

// PolicyUpdate carries the fields an update may change.
//
// PolicyID is deliberately absent: it is immutable, and a struct that cannot
// express the change is a stronger guarantee than a check that rejects it. Each
// field is a pointer so "not supplied" and "supplied as the zero value" stay
// distinguishable -- without that, omitting `enabled` would silently disable a
// policy.
type PolicyUpdate struct {
	Name        *string
	Description *string
	Severity    *domain.PolicySeverity
	Enabled     *bool
	Rules       *[]domain.PolicyRule
}

// UpdatePolicy applies an update and returns the stored definition.
//
// When the update leaves the policy inactive, its open violations are resolved
// in the SAME transaction. A rule that no longer applies must not keep a row on
// the dashboard until the next sweep happens to notice.
func (r *PolicyRepository) UpdatePolicy(
	ctx context.Context,
	policyID string,
	update PolicyUpdate,
	now time.Time,
) (domain.PolicyDefinition, error) {
	stamp := formatTime(now.UTC())

	tx, err := r.db.BeginTx(ctx, nil)
	if err != nil {
		return domain.PolicyDefinition{}, fmt.Errorf("begin policy update: %w", AsError(err))
	}
	defer func() { _ = tx.Rollback() }()

	existing, err := scanPolicyRow(tx.QueryRowContext(ctx, selectPolicyColumns+` WHERE policy_id = ?`, policyID))
	if err != nil {
		return domain.PolicyDefinition{}, err
	}
	// An archived policy is history. Editing one would change what a violation
	// row appears to have been measured against.
	if existing.Archived {
		return domain.PolicyDefinition{}, ErrNotFound
	}

	updated := existing
	if update.Name != nil {
		updated.Name = *update.Name
	}
	if update.Description != nil {
		updated.Description = *update.Description
	}
	if update.Severity != nil {
		updated.Severity = *update.Severity
	}
	if update.Enabled != nil {
		updated.Enabled = *update.Enabled
	}
	if update.Rules != nil {
		updated.Rules = *update.Rules
	}

	if updated.Name != existing.Name {
		taken, checkErr := txNameTaken(ctx, tx, updated.Name, policyID)
		if checkErr != nil {
			return domain.PolicyDefinition{}, checkErr
		}
		if taken {
			return domain.PolicyDefinition{}, ErrPolicyNameTaken
		}
	}

	rules, err := encodePolicyRules(updated.Rules)
	if err != nil {
		return domain.PolicyDefinition{}, err
	}
	enabled := 0
	if updated.Enabled {
		enabled = 1
	}

	if _, err := tx.ExecContext(ctx, `
		UPDATE policy_definitions
		SET name = ?, description = ?, severity = ?, enabled = ?,
		    rules_json = ?, rule_count = ?, updated_at = ?
		WHERE policy_id = ?`,
		updated.Name, updated.Description, string(updated.Severity), enabled,
		rules, len(updated.Rules), stamp, policyID,
	); err != nil {
		return domain.PolicyDefinition{}, fmt.Errorf("update policy: %w", AsError(err))
	}

	// The name is denormalised onto every violation so a list needs no join;
	// a rename must therefore reach them, or the dashboard would keep showing
	// the old one indefinitely.
	if updated.Name != existing.Name {
		if _, err := tx.ExecContext(ctx,
			`UPDATE policy_violations SET policy_name = ?, updated_at = ? WHERE policy_id = ?`,
			updated.Name, stamp, policyID); err != nil {
			return domain.PolicyDefinition{}, fmt.Errorf("rename policy violations: %w", AsError(err))
		}
	}

	if !updated.Active() {
		if _, err := resolveViolationsForPolicy(ctx, tx, policyID, stamp); err != nil {
			return domain.PolicyDefinition{}, err
		}
	}

	if err := tx.Commit(); err != nil {
		return domain.PolicyDefinition{}, fmt.Errorf("commit policy update: %w", AsError(err))
	}

	updated.UpdatedAt = now.UTC()
	return updated, nil
}

// ArchivePolicy withdraws a policy without destroying it.
//
// This is what DELETE /policies/{id} does, and the difference matters:
// policy_violations references this row, and the history must survive the rule
// being withdrawn. An auditor asking what the estate was failing last quarter
// must not get a different answer because someone tidied up this quarter.
//
// The policy's open violations are resolved in the same transaction, because
// the rule no longer applies and a resolved violation is the truthful record of
// that.
func (r *PolicyRepository) ArchivePolicy(ctx context.Context, policyID string, now time.Time) error {
	stamp := formatTime(now.UTC())

	tx, err := r.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin policy archive: %w", AsError(err))
	}
	defer func() { _ = tx.Rollback() }()

	result, err := tx.ExecContext(ctx, `
		UPDATE policy_definitions
		SET archived = 1, archived_at = ?, updated_at = ?
		WHERE policy_id = ? AND archived = 0`, stamp, stamp, policyID)
	if err != nil {
		return fmt.Errorf("archive policy: %w", AsError(err))
	}
	affected, err := result.RowsAffected()
	if err == nil && affected == 0 {
		return ErrNotFound
	}

	if _, err := resolveViolationsForPolicy(ctx, tx, policyID, stamp); err != nil {
		return err
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit policy archive: %w", AsError(err))
	}
	return nil
}

// resolveViolationsForPolicy closes every open violation belonging to a policy.
func resolveViolationsForPolicy(ctx context.Context, tx *sql.Tx, policyID, stamp string) (int64, error) {
	result, err := tx.ExecContext(ctx, `
		UPDATE policy_violations
		SET status = 'resolved', resolved_at = ?, updated_at = ?
		WHERE policy_id = ? AND status <> 'resolved'`, stamp, stamp, policyID)
	if err != nil {
		return 0, fmt.Errorf("resolve policy violations: %w", AsError(err))
	}
	// Used for a log line only; the update has already been applied.
	affected, _ := result.RowsAffected()
	return affected, nil
}

// GetPolicy returns one definition by its immutable id.
func (r *PolicyRepository) GetPolicy(ctx context.Context, policyID string) (domain.PolicyDefinition, error) {
	return scanPolicyRow(r.db.QueryRowContext(ctx, selectPolicyColumns+` WHERE policy_id = ?`, policyID))
}

// ListPolicies returns a page of definitions and the total matching the filter.
func (r *PolicyRepository) ListPolicies(
	ctx context.Context,
	filter PolicyFilter,
) ([]domain.PolicyDefinition, int, error) {
	where, args := policyWhere(filter)

	var total int
	if err := r.db.QueryRowContext(ctx,
		`SELECT COUNT(*) FROM policy_definitions`+where, args...).Scan(&total); err != nil {
		return nil, 0, fmt.Errorf("count policies: %w", AsError(err))
	}

	column, ok := policySortFields[filter.Sort]
	if !ok {
		column = "name"
	}
	direction := "DESC"
	if filter.Ascending {
		direction = "ASC"
	}

	page := filter.Page.normalise()
	// column and direction come from the allowlist above and a two-valued
	// switch; neither is caller text. Every VALUE is bound.
	query := selectPolicyColumns + where +
		` ORDER BY ` + column + ` ` + direction + `, id ` + direction +
		` LIMIT ? OFFSET ?`

	rows, err := r.db.QueryContext(ctx, query, append(args, page.Limit, page.Offset)...)
	if err != nil {
		return nil, 0, fmt.Errorf("query policies: %w", AsError(err))
	}
	defer func() { _ = rows.Close() }()

	policies, err := scanPolicies(rows)
	if err != nil {
		return nil, 0, err
	}
	return policies, total, nil
}

// ActivePolicies returns every policy that participates in evaluation.
//
// ONE query for the whole engine. The sweep loads this slice once and applies
// it to every container, which is what keeps a thousand-container pass from
// becoming a thousand policy queries.
//
// Unpaginated by design: the number of policies is bounded by configuration and
// is small by nature. A limit is applied anyway, as a backstop against a
// database that somehow holds more than the API would have accepted.
func (r *PolicyRepository) ActivePolicies(ctx context.Context, limit int) ([]domain.PolicyDefinition, error) {
	if limit < 1 {
		limit = 1000
	}
	rows, err := r.db.QueryContext(ctx,
		selectPolicyColumns+` WHERE archived = 0 AND enabled = 1 ORDER BY id ASC LIMIT ?`, limit)
	if err != nil {
		return nil, fmt.Errorf("query active policies: %w", AsError(err))
	}
	defer func() { _ = rows.Close() }()
	return scanPolicies(rows)
}

// CountPolicies returns the number of active and of total definitions.
func (r *PolicyRepository) CountPolicies(ctx context.Context) (active, total int, err error) {
	if err := r.db.QueryRowContext(ctx, `
		SELECT COALESCE(SUM(CASE WHEN archived = 0 AND enabled = 1 THEN 1 ELSE 0 END), 0),
		       COUNT(*)
		FROM policy_definitions`).Scan(&active, &total); err != nil {
		return 0, 0, fmt.Errorf("count policies: %w", AsError(err))
	}
	return active, total, nil
}

// nameTaken reports whether an unarchived policy already uses the name.
func (r *PolicyRepository) nameTaken(ctx context.Context, name, excluding string) (bool, error) {
	var count int
	err := r.db.QueryRowContext(ctx, `
		SELECT COUNT(*) FROM policy_definitions
		WHERE archived = 0 AND name = ? AND policy_id <> ?`, name, excluding).Scan(&count)
	if err != nil {
		return false, fmt.Errorf("check policy name: %w", AsError(err))
	}
	return count > 0, nil
}

// txNameTaken is nameTaken inside an open transaction.
func txNameTaken(ctx context.Context, tx *sql.Tx, name, excluding string) (bool, error) {
	var count int
	err := tx.QueryRowContext(ctx, `
		SELECT COUNT(*) FROM policy_definitions
		WHERE archived = 0 AND name = ? AND policy_id <> ?`, name, excluding).Scan(&count)
	if err != nil {
		return false, fmt.Errorf("check policy name: %w", AsError(err))
	}
	return count > 0, nil
}

// policyWhere builds the definition filter clause. Every value is bound.
func policyWhere(filter PolicyFilter) (string, []any) {
	clauses := make([]string, 0, 3)
	args := make([]any, 0, 3)

	if !filter.IncludeArchived {
		clauses = append(clauses, "archived = 0")
	}
	if filter.EnabledOnly {
		clauses = append(clauses, "enabled = 1")
	}
	if filter.Search != "" {
		// LIKE with a bound parameter. The wildcards are part of the BOUND
		// VALUE rather than of the SQL text, so a search term containing % or _
		// widens only its own match and cannot alter the statement.
		clauses = append(clauses, "(name LIKE ? ESCAPE '\\' OR description LIKE ? ESCAPE '\\')")
		pattern := "%" + escapeLikePattern(filter.Search) + "%"
		args = append(args, pattern, pattern)
	}

	if len(clauses) == 0 {
		return "", args
	}
	return " WHERE " + strings.Join(clauses, " AND "), args
}

// escapeLikePattern neutralises LIKE metacharacters in a search term.
//
// Without it, a search for "100%" matches every policy, which is a correctness
// bug rather than a security one -- but a term of many '%' characters also
// makes the match itself expensive, which is not.
func escapeLikePattern(term string) string {
	replacer := strings.NewReplacer(`\`, `\\`, `%`, `\%`, `_`, `\_`)
	return replacer.Replace(term)
}

// encodePolicyRules renders the rule list for storage.
func encodePolicyRules(rules []domain.PolicyRule) (string, error) {
	if rules == nil {
		rules = []domain.PolicyRule{}
	}
	encoded, err := json.Marshal(rules)
	if err != nil {
		return "", fmt.Errorf("encode policy rules: %w", err)
	}
	return string(encoded), nil
}

// policyScanner is satisfied by both *sql.Row and *sql.Rows.
type policyScanner interface {
	Scan(dest ...any) error
}

// scanPolicyRow reads one definition.
func scanPolicyRow(row policyScanner) (domain.PolicyDefinition, error) {
	var (
		policy     domain.PolicyDefinition
		severity   string
		enabled    int
		archived   int
		archivedAt sql.NullString
		rules      string
		created    string
		updated    string
	)
	err := row.Scan(&policy.ID, &policy.PolicyID, &policy.Name, &policy.Description,
		&severity, &enabled, &archived, &archivedAt, &rules, &created, &updated)
	if errors.Is(err, sql.ErrNoRows) {
		return domain.PolicyDefinition{}, ErrNotFound
	}
	if err != nil {
		return domain.PolicyDefinition{}, fmt.Errorf("scan policy: %w", AsError(err))
	}

	policy.Severity = domain.PolicySeverity(severity)
	policy.Enabled = enabled == 1
	policy.Archived = archived == 1

	if err := json.Unmarshal([]byte(rules), &policy.Rules); err != nil {
		return domain.PolicyDefinition{}, fmt.Errorf("decode policy rules: %w", err)
	}
	if policy.Rules == nil {
		policy.Rules = []domain.PolicyRule{}
	}

	if policy.CreatedAt, err = parseTime(created); err != nil {
		return domain.PolicyDefinition{}, err
	}
	if policy.UpdatedAt, err = parseTime(updated); err != nil {
		return domain.PolicyDefinition{}, err
	}
	if archivedAt.Valid && archivedAt.String != "" {
		parsed, parseErr := parseTime(archivedAt.String)
		if parseErr != nil {
			return domain.PolicyDefinition{}, parseErr
		}
		policy.ArchivedAt = &parsed
	}
	return policy, nil
}

func scanPolicies(rows *sql.Rows) ([]domain.PolicyDefinition, error) {
	policies := make([]domain.PolicyDefinition, 0, 16)
	for rows.Next() {
		policy, err := scanPolicyRow(rows)
		if err != nil {
			return nil, err
		}
		policies = append(policies, policy)
	}
	return policies, rows.Err()
}

// ------------------------------------------------------------- violations --

// PolicyViolationFilter narrows a violation listing.
//
// Every field is a closed vocabulary or an exact identifier validated by the
// API layer before it arrives. None of them becomes SQL text.
type PolicyViolationFilter struct {
	ContainerID string
	PolicyID    string
	RuleTypes   []domain.PolicyRuleType
	Severities  []domain.PolicySeverity
	Statuses    []domain.PolicyViolationStatus
	// OpenOnly restricts to violations that are not resolved.
	OpenOnly bool

	Sort      string
	Ascending bool
	Page      Page
}

const selectViolationColumns = `
	SELECT id, policy_id, policy_name, container_id, container_name,
	       rule_type, severity, detected_at, last_seen_at, resolved_at,
	       inventory_generation, observed, expected, reason,
	       status, note, status_changed_at
	FROM policy_violations`

// ReconcilePolicy persists one container's compliance pass in a single
// transaction.
//
// # Why one transaction
//
// A pass is a statement about a container at one moment: these rules fail, and
// no others do. Writing the failures and the resolutions separately would leave
// a window where a reader sees both a new violation and the stale rows the same
// pass just disproved.
//
// # Operator intent is preserved
//
// An acknowledgement or exemption SURVIVES re-evaluation, and re-evaluation
// keeps happening: only the rendered values, timestamps and severity are
// refreshed. A violation that had been resolved and fails again returns to
// active, because the world changed back and that is engine-owned news rather
// than an operator's opinion.
func (r *PolicyRepository) ReconcilePolicy(
	ctx context.Context,
	evaluation domain.PolicyEvaluation,
	violations []domain.PolicyViolation,
	now time.Time,
) (UpsertResult, error) {
	var result UpsertResult
	stamp := formatTime(now.UTC())

	tx, err := r.db.BeginTx(ctx, nil)
	if err != nil {
		return result, fmt.Errorf("begin policy transaction: %w", AsError(err))
	}
	defer func() { _ = tx.Rollback() }()

	seen := make([]string, 0, len(violations))
	for _, violation := range violations {
		inserted, err := upsertViolation(ctx, tx, violation, stamp)
		if err != nil {
			return result, err
		}
		if inserted {
			result.Inserted++
		} else {
			result.Updated++
		}
		seen = append(seen, policyIdentityKey(violation))
	}

	resolved, err := resolveCompliantViolations(ctx, tx, evaluation, seen, stamp)
	if err != nil {
		return result, err
	}
	result.Resolved = resolved

	if err := recordPolicyEvaluation(ctx, tx, evaluation, stamp); err != nil {
		return result, err
	}

	if err := tx.Commit(); err != nil {
		return result, fmt.Errorf("commit policy evaluation: %w", AsError(err))
	}
	return result, nil
}

// upsertViolation writes one failed rule, preserving operator intent.
//
// Reports whether the row was newly inserted, which is what distinguishes a new
// violation from one that is merely still failing.
func upsertViolation(ctx context.Context, tx *sql.Tx, violation domain.PolicyViolation, stamp string) (bool, error) {
	// ON CONFLICT over the identity index. detected_at is deliberately NOT
	// updated: the age of a violation is the age of the non-compliance, and
	// moving it on every pass would make everything look like it started just
	// now.
	//
	// The status expression is the operator-intent rule in SQL: a resolved
	// violation seen again returns to active; acknowledged and exempted are
	// left alone, so an acknowledgement survives without suppressing anything.
	//
	// RETURNING created_at tells insert from update in the SAME statement. A
	// follow-up SELECT would be a second round trip per failing rule, inside
	// the transaction that holds the single SQLite writer.
	var createdAt string
	err := tx.QueryRowContext(ctx, `
		INSERT INTO policy_violations
			(policy_id, policy_name, container_id, container_name,
			 rule_type, severity, detected_at, last_seen_at,
			 inventory_generation, observed, expected, reason,
			 status, created_at, updated_at)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active', ?, ?)
		ON CONFLICT (container_id, policy_id, rule_type) DO UPDATE SET
			policy_name          = excluded.policy_name,
			container_name       = excluded.container_name,
			severity             = excluded.severity,
			last_seen_at         = excluded.last_seen_at,
			inventory_generation = excluded.inventory_generation,
			observed             = excluded.observed,
			expected             = excluded.expected,
			reason               = excluded.reason,
			resolved_at          = NULL,
			status               = CASE
				WHEN policy_violations.status = 'resolved' THEN 'active'
				ELSE policy_violations.status
			END,
			updated_at = excluded.updated_at
		RETURNING created_at`,
		violation.PolicyID, violation.PolicyName, violation.ContainerID, violation.ContainerName,
		string(violation.RuleType), string(violation.Severity), stamp, stamp,
		violation.InventoryGeneration, violation.Observed, violation.Expected, violation.Reason,
		stamp, stamp,
	).Scan(&createdAt)
	if err != nil {
		return false, fmt.Errorf("upsert policy violation: %w", AsError(err))
	}

	// created_at is only ever written by the INSERT arm, so a row whose
	// created_at is this pass's stamp is one this pass created.
	return createdAt == stamp, nil
}

// resolveCompliantViolations marks the rules this pass found the container
// compliant with.
func resolveCompliantViolations(
	ctx context.Context,
	tx *sql.Tx,
	evaluation domain.PolicyEvaluation,
	seen []string,
	stamp string,
) (int, error) {
	// An INCOMPLETE pass resolves nothing. It did not establish that the rules
	// it never applied now pass; it established that it stopped applying them.
	// Resolving on that basis would silently clear real non-compliance, which
	// is the worst failure this feature can have.
	if !evaluation.Complete {
		return 0, nil
	}

	query := `
		UPDATE policy_violations
		SET status = 'resolved', resolved_at = ?, updated_at = ?
		WHERE container_id = ? AND status <> 'resolved'`
	args := []any{stamp, stamp, evaluation.ContainerID}

	if len(seen) > 0 {
		// A placeholder run generated from a slice LENGTH, never from content.
		// The identity keys travel as bound parameters.
		//
		// char(31) rather than a '\x1f' literal: SQLite has no backslash
		// escapes in string literals, so '\x1f' would be the four characters
		// backslash-x-1-f. Two identities could then collide through a policy
		// id containing that text, and a collision here silently resolves a
		// violation that still stands.
		query += ` AND (policy_id || char(31) || rule_type) NOT IN (` +
			placeholders(len(seen)) + `)`
		for _, key := range seen {
			args = append(args, key)
		}
	}

	result, err := tx.ExecContext(ctx, query, args...)
	if err != nil {
		return 0, fmt.Errorf("resolve policy violations: %w", AsError(err))
	}

	// The count is used for a log line only, so a driver that cannot report it
	// is not worth failing the transaction over -- the resolutions have already
	// been applied. Discarded explicitly rather than returned beside a real
	// error.
	affected, _ := result.RowsAffected()
	return int(affected), nil
}

// policyIdentityKey renders the identity used by the NOT IN clause above.
//
// The separator is a unit separator (0x1f), which cannot occur in a generated
// policy id nor in a rule type from the closed vocabulary. Using a character
// that could appear in either would let two identities collide and silently
// resolve a violation that still stands.
func policyIdentityKey(violation domain.PolicyViolation) string {
	return violation.PolicyID + "\x1f" + string(violation.RuleType)
}

// recordPolicyEvaluation stores the pass, so "compliant" and "never evaluated"
// stay distinguishable.
func recordPolicyEvaluation(
	ctx context.Context,
	tx *sql.Tx,
	evaluation domain.PolicyEvaluation,
	stamp string,
) error {
	complete, compliant := 0, 0
	if evaluation.Complete {
		complete = 1
	}
	// Belt and braces with the CHECK constraint: compliant is asserted only for
	// a complete pass that found nothing.
	if evaluation.Complete && evaluation.ViolationCount == 0 {
		compliant = 1
	}

	if _, err := tx.ExecContext(ctx, `
		INSERT INTO policy_evaluations
			(container_id, container_name, evaluated_at, inventory_generation,
			 policies_evaluated, rules_evaluated, violation_count,
			 compliant, complete, reason)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
		ON CONFLICT (container_id) DO UPDATE SET
			container_name       = excluded.container_name,
			evaluated_at         = excluded.evaluated_at,
			inventory_generation = excluded.inventory_generation,
			policies_evaluated   = excluded.policies_evaluated,
			rules_evaluated      = excluded.rules_evaluated,
			violation_count      = excluded.violation_count,
			compliant            = excluded.compliant,
			complete             = excluded.complete,
			reason               = excluded.reason`,
		evaluation.ContainerID, evaluation.ContainerName, stamp,
		evaluation.InventoryGeneration, evaluation.PoliciesEvaluated,
		evaluation.RulesEvaluated, evaluation.ViolationCount,
		compliant, complete, evaluation.Reason,
	); err != nil {
		return fmt.Errorf("record policy evaluation: %w", AsError(err))
	}
	return nil
}

// ListViolations returns a page of violations and the total matching the
// filter.
func (r *PolicyRepository) ListViolations(
	ctx context.Context,
	filter PolicyViolationFilter,
) ([]domain.PolicyViolation, int, error) {
	where, args := violationWhere(filter)

	var total int
	if err := r.db.QueryRowContext(ctx,
		`SELECT COUNT(*) FROM policy_violations`+where, args...).Scan(&total); err != nil {
		return nil, 0, fmt.Errorf("count policy violations: %w", AsError(err))
	}

	column, ok := policyViolationSortFields[filter.Sort]
	if !ok {
		column = "detected_at"
	}
	direction := "DESC"
	if filter.Ascending {
		direction = "ASC"
	}

	page := filter.Page.normalise()
	query := selectViolationColumns + where +
		` ORDER BY ` + column + ` ` + direction + `, id ` + direction +
		` LIMIT ? OFFSET ?`

	rows, err := r.db.QueryContext(ctx, query, append(args, page.Limit, page.Offset)...)
	if err != nil {
		return nil, 0, fmt.Errorf("query policy violations: %w", AsError(err))
	}
	defer func() { _ = rows.Close() }()

	violations, err := scanViolations(rows)
	if err != nil {
		return nil, 0, err
	}
	return violations, total, nil
}

// GetViolation returns one violation.
func (r *PolicyRepository) GetViolation(ctx context.Context, id int64) (domain.PolicyViolation, error) {
	rows, err := r.db.QueryContext(ctx, selectViolationColumns+` WHERE id = ?`, id)
	if err != nil {
		return domain.PolicyViolation{}, fmt.Errorf("query policy violation: %w", AsError(err))
	}
	defer func() { _ = rows.Close() }()

	violations, err := scanViolations(rows)
	if err != nil {
		return domain.PolicyViolation{}, err
	}
	if len(violations) == 0 {
		return domain.PolicyViolation{}, ErrNotFound
	}
	return violations[0], nil
}

// UpdateViolationStatus applies an operator's status transition.
//
// The vocabulary is validated by the API against
// domain.OperatorPolicyStatuses before it arrives, and the CHECK constraint is
// the backstop. Nothing here can set active or resolved: those are the
// engine's, and a caller asserting "resolved" would be asserting a fact about
// the world rather than an intent.
//
// The transition does NOT suppress re-evaluation. The next pass still applies
// the rule, still refreshes last_seen_at, and still resolves the row the moment
// the container complies.
func (r *PolicyRepository) UpdateViolationStatus(
	ctx context.Context,
	id int64,
	status domain.PolicyViolationStatus,
	note string,
	now time.Time,
) (domain.PolicyViolation, error) {
	stamp := formatTime(now.UTC())

	result, err := r.db.ExecContext(ctx, `
		UPDATE policy_violations
		SET status = ?, note = ?, status_changed_at = ?, updated_at = ?
		WHERE id = ?`,
		string(status), note, stamp, stamp, id)
	if err != nil {
		return domain.PolicyViolation{}, fmt.Errorf("update policy violation status: %w", AsError(err))
	}
	affected, err := result.RowsAffected()
	if err == nil && affected == 0 {
		return domain.PolicyViolation{}, ErrNotFound
	}
	return r.GetViolation(ctx, id)
}

// PolicyEvaluation returns the most recent compliance pass for one container.
func (r *PolicyRepository) PolicyEvaluation(
	ctx context.Context,
	containerID string,
) (domain.PolicyEvaluation, error) {
	var (
		evaluation domain.PolicyEvaluation
		evaluated  string
		compliant  int
		complete   int
	)
	err := r.db.QueryRowContext(ctx, `
		SELECT container_id, container_name, evaluated_at, inventory_generation,
		       policies_evaluated, rules_evaluated, violation_count,
		       compliant, complete, reason
		FROM policy_evaluations WHERE container_id = ?`, containerID,
	).Scan(&evaluation.ContainerID, &evaluation.ContainerName, &evaluated,
		&evaluation.InventoryGeneration, &evaluation.PoliciesEvaluated,
		&evaluation.RulesEvaluated, &evaluation.ViolationCount,
		&compliant, &complete, &evaluation.Reason)
	if errors.Is(err, sql.ErrNoRows) {
		return domain.PolicyEvaluation{}, ErrNotFound
	}
	if err != nil {
		return domain.PolicyEvaluation{}, fmt.Errorf("read policy evaluation: %w", AsError(err))
	}

	evaluation.Compliant = compliant == 1
	evaluation.Complete = complete == 1
	if evaluation.EvaluatedAt, err = parseTime(evaluated); err != nil {
		return domain.PolicyEvaluation{}, err
	}
	return evaluation, nil
}

// PolicySummary computes the compliance aggregate.
//
// Grouped queries plus a few scalars, rather than one list the caller counts.
// Each is served by an index and each returns at most a handful of rows, so the
// cost is proportional to the number of DISTINCT severities, statuses and rule
// types -- constants -- not to the number of violations.
func (r *PolicyRepository) PolicySummary(ctx context.Context) (domain.PolicySummary, error) {
	summary := domain.PolicySummary{
		BySeverity: make(map[domain.PolicySeverity]int, len(domain.PolicySeverities)),
		ByStatus:   make(map[domain.PolicyViolationStatus]int, len(domain.PolicyViolationStatuses)),
		ByRule:     make(map[domain.PolicyRuleType]int, len(domain.PolicyRuleTypes)),
	}

	active, total, err := r.CountPolicies(ctx)
	if err != nil {
		return summary, err
	}
	summary.Policies, summary.PoliciesTotal = active, total

	// Severity and rule counts describe OPEN violations only. Including
	// resolved history would make a dashboard's "3 critical" mean "3 critical
	// at some point since installation", which is not what anyone reads it as.
	for _, group := range []struct {
		query string
		apply func(key string, count int)
	}{
		{
			`SELECT severity, COUNT(*) FROM policy_violations WHERE status <> 'resolved' GROUP BY severity`,
			func(key string, count int) { summary.BySeverity[domain.PolicySeverity(key)] = count },
		},
		{
			`SELECT status, COUNT(*) FROM policy_violations GROUP BY status`,
			func(key string, count int) { summary.ByStatus[domain.PolicyViolationStatus(key)] = count },
		},
		{
			`SELECT rule_type, COUNT(*) FROM policy_violations WHERE status <> 'resolved' GROUP BY rule_type`,
			func(key string, count int) { summary.ByRule[domain.PolicyRuleType(key)] = count },
		},
	} {
		if err := r.scanPolicyCounts(ctx, group.query, group.apply); err != nil {
			return summary, err
		}
	}

	if err := r.db.QueryRowContext(ctx, `
		SELECT COUNT(*),
		       COALESCE(SUM(CASE WHEN status <> 'resolved' THEN 1 ELSE 0 END), 0)
		FROM policy_violations`).Scan(&summary.Total, &summary.Open); err != nil {
		return summary, fmt.Errorf("count policy violation totals: %w", AsError(err))
	}

	if err := r.db.QueryRowContext(ctx, `
		SELECT COUNT(DISTINCT container_id) FROM policy_violations WHERE status <> 'resolved'`,
	).Scan(&summary.ContainersNonCompliant); err != nil {
		return summary, fmt.Errorf("count non-compliant containers: %w", AsError(err))
	}

	var (
		lastEvaluated sql.NullString
		incomplete    int
	)
	if err := r.db.QueryRowContext(ctx, `
		SELECT COUNT(*), MAX(evaluated_at),
		       COALESCE(SUM(CASE WHEN compliant = 1 THEN 1 ELSE 0 END), 0),
		       COALESCE(SUM(CASE WHEN complete = 0 THEN 1 ELSE 0 END), 0)
		FROM policy_evaluations`,
	).Scan(&summary.ContainersEvaluated, &lastEvaluated,
		&summary.ContainersCompliant, &incomplete); err != nil {
		return summary, fmt.Errorf("read policy evaluations: %w", AsError(err))
	}
	summary.Incomplete = incomplete > 0

	if lastEvaluated.Valid && lastEvaluated.String != "" {
		parsed, err := parseTime(lastEvaluated.String)
		if err != nil {
			return summary, err
		}
		summary.LastEvaluatedAt = &parsed
	}
	return summary, nil
}

// PruneResolvedViolations deletes resolved violations older than the cutoff.
//
// Resolved history is the dimension that grows without bound on a busy host.
// Open violations are never pruned: an unreviewed failure does not become less
// true with age.
func (r *PolicyRepository) PruneResolvedViolations(
	ctx context.Context,
	cutoff time.Time,
	batch int,
) (int64, error) {
	if batch < 1 {
		batch = 500
	}
	result, err := r.db.ExecContext(ctx, `
		DELETE FROM policy_violations
		WHERE id IN (
			SELECT id FROM policy_violations
			WHERE status = 'resolved' AND resolved_at IS NOT NULL AND resolved_at < ?
			LIMIT ?
		)`, formatTime(cutoff.UTC()), batch)
	if err != nil {
		return 0, fmt.Errorf("prune resolved policy violations: %w", AsError(err))
	}

	// Reported for logging only; the deletion has already happened.
	removed, _ := result.RowsAffected()
	return removed, nil
}

// scanPolicyCounts runs a two-column GROUP BY and applies each row.
func (r *PolicyRepository) scanPolicyCounts(ctx context.Context, query string, apply func(string, int)) error {
	rows, err := r.db.QueryContext(ctx, query)
	if err != nil {
		return fmt.Errorf("aggregate policy violations: %w", AsError(err))
	}
	defer func() { _ = rows.Close() }()

	for rows.Next() {
		var (
			key   string
			count int
		)
		if err := rows.Scan(&key, &count); err != nil {
			return fmt.Errorf("scan policy aggregate: %w", err)
		}
		apply(key, count)
	}
	return rows.Err()
}

// violationWhere builds the filter clause. Every value is bound; only the
// placeholder RUN length varies with the input.
func violationWhere(filter PolicyViolationFilter) (string, []any) {
	clauses := make([]string, 0, 6)
	args := make([]any, 0, 8)

	if filter.ContainerID != "" {
		clauses = append(clauses, "container_id = ?")
		args = append(args, filter.ContainerID)
	}
	if filter.PolicyID != "" {
		clauses = append(clauses, "policy_id = ?")
		args = append(args, filter.PolicyID)
	}
	if filter.OpenOnly {
		clauses = append(clauses, "status <> 'resolved'")
	}

	if len(filter.RuleTypes) > 0 {
		clauses = append(clauses, "rule_type IN ("+placeholders(len(filter.RuleTypes))+")")
		for _, ruleType := range filter.RuleTypes {
			args = append(args, string(ruleType))
		}
	}
	if len(filter.Severities) > 0 {
		clauses = append(clauses, "severity IN ("+placeholders(len(filter.Severities))+")")
		for _, severity := range filter.Severities {
			args = append(args, string(severity))
		}
	}
	if len(filter.Statuses) > 0 {
		clauses = append(clauses, "status IN ("+placeholders(len(filter.Statuses))+")")
		for _, status := range filter.Statuses {
			args = append(args, string(status))
		}
	}

	if len(clauses) == 0 {
		return "", args
	}
	return " WHERE " + strings.Join(clauses, " AND "), args
}

func scanViolations(rows *sql.Rows) ([]domain.PolicyViolation, error) {
	violations := make([]domain.PolicyViolation, 0, 16)

	for rows.Next() {
		var (
			violation     domain.PolicyViolation
			ruleType      string
			severity      string
			status        string
			detected      string
			lastSeen      string
			resolved      sql.NullString
			statusChanged sql.NullString
		)
		if err := rows.Scan(
			&violation.ID, &violation.PolicyID, &violation.PolicyName,
			&violation.ContainerID, &violation.ContainerName,
			&ruleType, &severity, &detected, &lastSeen, &resolved,
			&violation.InventoryGeneration, &violation.Observed,
			&violation.Expected, &violation.Reason,
			&status, &violation.Note, &statusChanged,
		); err != nil {
			return nil, fmt.Errorf("scan policy violation: %w", err)
		}

		violation.RuleType = domain.PolicyRuleType(ruleType)
		violation.Severity = domain.PolicySeverity(severity)
		violation.Status = domain.PolicyViolationStatus(status)

		var err error
		if violation.DetectedAt, err = parseTime(detected); err != nil {
			return nil, err
		}
		if violation.LastSeenAt, err = parseTime(lastSeen); err != nil {
			return nil, err
		}
		if resolved.Valid && resolved.String != "" {
			parsed, parseErr := parseTime(resolved.String)
			if parseErr != nil {
				return nil, parseErr
			}
			violation.ResolvedAt = &parsed
		}
		if statusChanged.Valid && statusChanged.String != "" {
			parsed, parseErr := parseTime(statusChanged.String)
			if parseErr != nil {
				return nil, parseErr
			}
			violation.StatusChangedAt = &parsed
		}

		violations = append(violations, violation)
	}
	return violations, rows.Err()
}
