package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/Aznyi/HarborMaster/internal/domain"
)

// UpdatePolicyRepository owns persistence for automation rules.
//
// # Deliberately not PolicyRepository
//
// A compliance policy REPORTS and an update policy ACTS. Two repositories, two
// tables, two sets of SQL, so no query, no filter, and no future refactor can
// make one become the other. The cost is duplication that reads similar; the
// benefit is that "make policies editable by operators" can never accidentally
// hand out the ability to schedule container recreation.
//
// # Bounded reads
//
// Every list is paginated and every sort field comes from an allowlist. The
// scheduler loads every enabled policy ONCE per pass through ActivePolicies and
// applies that slice to each container in memory, so a pass costs one query
// regardless of how many containers the host runs.
type UpdatePolicyRepository struct {
	db *sql.DB
}

// ErrUpdatePolicyNameTaken reports a duplicate policy name.
//
// The name is not the identifier -- the immutable policy id is -- but two rules
// called "Nightly patches" make an automation history unreadable, so the name
// is unique among policies that are not archived.
var ErrUpdatePolicyNameTaken = errors.New("an update policy with that name already exists")

// updatePolicySortFields is the allowlist of sortable columns.
//
// An allowlist rather than validation-by-rejection: the value becomes part of
// the SQL text, so the only safe design is one where caller input SELECTS from
// a fixed set of literals rather than contributing to it.
var updatePolicySortFields = map[string]string{
	"name":      "name",
	"priority":  "priority",
	"createdAt": "created_at",
	"updatedAt": "updated_at",
	"mode":      "mode",
	"strategy":  "strategy",
	"id":        "id",
}

// ValidUpdatePolicySortField reports whether field names a sortable column.
func ValidUpdatePolicySortField(field string) bool {
	_, ok := updatePolicySortFields[field]
	return ok
}

// UpdatePolicySortFields lists the sortable fields, for error messages.
func UpdatePolicySortFields() []string {
	fields := make([]string, 0, len(updatePolicySortFields))
	for field := range updatePolicySortFields {
		fields = append(fields, field)
	}
	sortStrings(fields)
	return fields
}

// UpdatePolicyFilter narrows a policy listing.
type UpdatePolicyFilter struct {
	EnabledOnly bool
	// IncludeArchived includes withdrawn policies. Excluded by default: an
	// archived policy is history, and a list dominated by history buries the
	// rules actually in force.
	IncludeArchived bool
	// Modes restricts to a closed vocabulary the API validated. Never SQL text.
	Modes  []domain.AutomationMode
	Search string

	Sort      string
	Ascending bool
	Page      Page
}

const selectUpdatePolicyColumns = `
	SELECT id, policy_id, name, description, enabled, archived, priority,
	       scope, strategy, mode, minimum_recommendation,
	       selector_json, window_json, limits_json, failure_json,
	       created_at, updated_at
	FROM update_policies`

// CreateUpdatePolicy stores a new rule.
//
// The policy id is generated by the caller (domain.NewUpdatePolicyID) from the
// system entropy source and is never derived from caller input, so a caller can
// neither choose one nor collide with one.
func (r *UpdatePolicyRepository) CreateUpdatePolicy(
	ctx context.Context,
	policy domain.UpdatePolicy,
	now time.Time,
) (domain.UpdatePolicy, error) {
	documents, err := encodeUpdatePolicyDocuments(policy)
	if err != nil {
		return domain.UpdatePolicy{}, err
	}

	taken, err := r.nameTaken(ctx, policy.Name, "")
	if err != nil {
		return domain.UpdatePolicy{}, err
	}
	if taken {
		return domain.UpdatePolicy{}, ErrUpdatePolicyNameTaken
	}

	stamp := formatTime(now.UTC())
	result, err := r.db.ExecContext(ctx, `
		INSERT INTO update_policies
			(policy_id, name, description, enabled, archived, priority,
			 scope, strategy, mode, minimum_recommendation,
			 selector_json, window_json, limits_json, failure_json,
			 created_at, updated_at)
		VALUES (?, ?, ?, ?, 0, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		policy.PolicyID, policy.Name, policy.Description, boolToInt(policy.Enabled),
		policy.Priority, string(policy.Scope), string(policy.Strategy), string(policy.Mode),
		string(policy.MinimumRecommendation),
		documents.selector, documents.window, documents.limits, documents.failure,
		stamp, stamp)
	if err != nil {
		return domain.UpdatePolicy{}, fmt.Errorf("insert update policy: %w", AsError(err))
	}

	id, _ := result.LastInsertId()
	policy.ID = id
	policy.Archived = false
	policy.CreatedAt = stamp
	policy.UpdatedAt = stamp
	return policy, nil
}

// UpdatePolicyChange carries the fields an edit may change.
//
// PolicyID is deliberately absent: it is immutable, and a struct that cannot
// express the change is a stronger guarantee than a check that rejects it. Each
// field is a pointer so "not supplied" and "supplied as the zero value" stay
// distinguishable -- without that, omitting `enabled` would silently disable a
// policy, which for an automation rule is a change of behaviour in both
// directions.
type UpdatePolicyChange struct {
	Name                  *string
	Description           *string
	Enabled               *bool
	Priority              *int
	Scope                 *domain.UpdateScope
	Selector              *domain.UpdateSelector
	Strategy              *domain.UpdateStrategy
	MinimumRecommendation *domain.Recommendation
	Mode                  *domain.AutomationMode
	Window                *domain.MaintenanceWindow
	Limits                *domain.UpdateLimits
	Failure               *domain.UpdateFailureHandling
}

// ApplyUpdatePolicy applies a change and returns the stored rule.
//
// Read-modify-write inside one transaction, so two concurrent edits cannot
// interleave into a policy neither administrator wrote.
func (r *UpdatePolicyRepository) ApplyUpdatePolicy(
	ctx context.Context,
	policyID string,
	change UpdatePolicyChange,
	now time.Time,
) (domain.UpdatePolicy, error) {
	tx, err := r.db.BeginTx(ctx, nil)
	if err != nil {
		return domain.UpdatePolicy{}, fmt.Errorf("begin update policy edit: %w", AsError(err))
	}
	defer func() { _ = tx.Rollback() }()

	existing, err := scanUpdatePolicyRow(
		tx.QueryRowContext(ctx, selectUpdatePolicyColumns+` WHERE policy_id = ?`, policyID))
	if err != nil {
		return domain.UpdatePolicy{}, err
	}
	// An archived policy is history. Editing one would change what a decision
	// row appears to have been made under.
	if existing.Archived {
		return domain.UpdatePolicy{}, ErrNotFound
	}

	merged := existing
	if change.Name != nil {
		merged.Name = *change.Name
	}
	if change.Description != nil {
		merged.Description = *change.Description
	}
	if change.Enabled != nil {
		merged.Enabled = *change.Enabled
	}
	if change.Priority != nil {
		merged.Priority = *change.Priority
	}
	// Scope before selector, so the two are merged in the order the validator
	// reads them. An edit that supplies neither leaves both alone, which is what
	// makes a partial edit unable to change how wide a policy reaches.
	if change.Scope != nil {
		merged.Scope = *change.Scope
	}
	if change.Selector != nil {
		merged.Selector = *change.Selector
	}
	if change.Strategy != nil {
		merged.Strategy = *change.Strategy
	}
	if change.MinimumRecommendation != nil {
		merged.MinimumRecommendation = *change.MinimumRecommendation
	}
	if change.Mode != nil {
		merged.Mode = *change.Mode
	}
	if change.Window != nil {
		merged.Window = *change.Window
	}
	if change.Limits != nil {
		merged.Limits = *change.Limits
	}
	if change.Failure != nil {
		merged.Failure = *change.Failure
	}

	if merged.Name != existing.Name {
		taken, err := txUpdatePolicyNameTaken(ctx, tx, merged.Name, policyID)
		if err != nil {
			return domain.UpdatePolicy{}, err
		}
		if taken {
			return domain.UpdatePolicy{}, ErrUpdatePolicyNameTaken
		}
	}

	documents, err := encodeUpdatePolicyDocuments(merged)
	if err != nil {
		return domain.UpdatePolicy{}, err
	}

	stamp := formatTime(now.UTC())
	if _, err := tx.ExecContext(ctx, `
		UPDATE update_policies
		   SET name = ?, description = ?, enabled = ?, priority = ?,
		       scope = ?, strategy = ?, mode = ?, minimum_recommendation = ?,
		       selector_json = ?, window_json = ?, limits_json = ?, failure_json = ?,
		       updated_at = ?
		 WHERE policy_id = ? AND archived = 0`,
		merged.Name, merged.Description, boolToInt(merged.Enabled), merged.Priority,
		string(merged.Scope), string(merged.Strategy), string(merged.Mode),
		string(merged.MinimumRecommendation),
		documents.selector, documents.window, documents.limits, documents.failure,
		stamp, policyID); err != nil {
		return domain.UpdatePolicy{}, fmt.Errorf("update policy: %w", AsError(err))
	}

	if err := tx.Commit(); err != nil {
		return domain.UpdatePolicy{}, fmt.Errorf("commit update policy edit: %w", AsError(err))
	}
	merged.UpdatedAt = stamp
	return merged, nil
}

// ArchiveUpdatePolicy withdraws a rule without deleting the history that names
// it.
//
// The one way a policy leaves service. There is no DELETE: automation decisions
// and pauses reference this row, and an auditor asking what changed the estate
// in March must not get a different answer because somebody tidied up in April.
func (r *UpdatePolicyRepository) ArchiveUpdatePolicy(
	ctx context.Context,
	policyID string,
	now time.Time,
) error {
	stamp := formatTime(now.UTC())
	result, err := r.db.ExecContext(ctx, `
		UPDATE update_policies
		   SET archived = 1, archived_at = ?, enabled = 0, updated_at = ?
		 WHERE policy_id = ? AND archived = 0`,
		stamp, stamp, policyID)
	if err != nil {
		return fmt.Errorf("archive update policy: %w", AsError(err))
	}
	affected, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("archive update policy: %w", AsError(err))
	}
	if affected == 0 {
		return ErrNotFound
	}
	return nil
}

// UpdatePolicyByID reads one rule.
func (r *UpdatePolicyRepository) UpdatePolicyByID(
	ctx context.Context,
	policyID string,
) (domain.UpdatePolicy, error) {
	return scanUpdatePolicyRow(
		r.db.QueryRowContext(ctx, selectUpdatePolicyColumns+` WHERE policy_id = ?`, policyID))
}

// ActivePolicies returns every policy the scheduler must consider, in the order
// the selection rule needs.
//
// Ordered here rather than in Go so the index serves the sort. The result is
// still passed to domain.SelectUpdatePolicy, which re-applies the ordering
// rule: the database's order is an optimisation, never the authority.
//
// Bounded by maxActiveUpdatePolicies. An estate cannot have more automation
// rules than that without something having gone wrong, and an unbounded load
// on every pass is how a scheduler becomes the thing that takes the host down.
func (r *UpdatePolicyRepository) ActivePolicies(ctx context.Context) ([]domain.UpdatePolicy, error) {
	rows, err := r.db.QueryContext(ctx, selectUpdatePolicyColumns+`
		 WHERE archived = 0 AND enabled = 1
		 ORDER BY priority DESC, policy_id ASC
		 LIMIT ?`, maxActiveUpdatePolicies)
	if err != nil {
		return nil, fmt.Errorf("load active update policies: %w", AsError(err))
	}
	defer func() { _ = rows.Close() }()

	policies := make([]domain.UpdatePolicy, 0, 8)
	for rows.Next() {
		policy, err := scanUpdatePolicy(rows)
		if err != nil {
			return nil, err
		}
		policies = append(policies, policy)
	}
	return policies, rows.Err()
}

// maxActiveUpdatePolicies bounds one scheduler pass's policy load.
const maxActiveUpdatePolicies = 200

// ListUpdatePolicies returns a bounded page.
func (r *UpdatePolicyRepository) ListUpdatePolicies(
	ctx context.Context,
	filter UpdatePolicyFilter,
) ([]domain.UpdatePolicy, int, error) {
	page := filter.Page.normalise()

	where := []string{"1 = 1"}
	args := make([]any, 0, 6)

	if !filter.IncludeArchived {
		where = append(where, "archived = 0")
	}
	if filter.EnabledOnly {
		where = append(where, "enabled = 1")
	}
	if len(filter.Modes) > 0 {
		// Placeholders, one per value. The vocabulary is closed and validated
		// by the API, and it is still bound rather than interpolated.
		placeholders := make([]string, 0, len(filter.Modes))
		for _, mode := range filter.Modes {
			placeholders = append(placeholders, "?")
			args = append(args, string(mode))
		}
		where = append(where, "mode IN ("+strings.Join(placeholders, ", ")+")")
	}
	if trimmed := strings.TrimSpace(filter.Search); trimmed != "" {
		// LIKE with an escaped pattern. The wildcards a caller typed are
		// escaped so a search for "100%" is a search for that text rather than
		// a pattern that matches the whole table.
		where = append(where, `(name LIKE ? ESCAPE '\' OR description LIKE ? ESCAPE '\')`)
		pattern := "%" + escapeLike(trimmed) + "%"
		args = append(args, pattern, pattern)
	}
	clause := " WHERE " + strings.Join(where, " AND ")

	var total int
	if err := r.db.QueryRowContext(ctx,
		`SELECT COUNT(*) FROM update_policies`+clause, args...).Scan(&total); err != nil {
		return nil, 0, fmt.Errorf("count update policies: %w", AsError(err))
	}

	column, ok := updatePolicySortFields[filter.Sort]
	if !ok {
		column = "priority"
	}
	direction := "DESC"
	if filter.Ascending {
		direction = "ASC"
	}
	// Every fragment concatenated below is a literal chosen by the allowlist
	// above. No caller string reaches the SQL text.
	query := selectUpdatePolicyColumns + clause +
		" ORDER BY " + column + " " + direction + ", id DESC LIMIT ? OFFSET ?"
	args = append(args, page.Limit, page.Offset)

	rows, err := r.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, 0, fmt.Errorf("list update policies: %w", AsError(err))
	}
	defer func() { _ = rows.Close() }()

	policies := make([]domain.UpdatePolicy, 0, page.Limit)
	for rows.Next() {
		policy, err := scanUpdatePolicy(rows)
		if err != nil {
			return nil, 0, err
		}
		policies = append(policies, policy)
	}
	return policies, total, rows.Err()
}

// CountUpdatePolicies returns the total and enabled counts for the dashboard.
func (r *UpdatePolicyRepository) CountUpdatePolicies(ctx context.Context) (total, enabled int, err error) {
	err = r.db.QueryRowContext(ctx, `
		SELECT COUNT(*), COALESCE(SUM(enabled), 0)
		  FROM update_policies
		 WHERE archived = 0`).Scan(&total, &enabled)
	if err != nil {
		return 0, 0, fmt.Errorf("count update policies: %w", AsError(err))
	}
	return total, enabled, nil
}

// ------------------------------------------------------------- encoding --

// updatePolicyDocuments holds the four JSON columns.
type updatePolicyDocuments struct {
	selector string
	window   string
	limits   string
	failure  string
}

// encodeUpdatePolicyDocuments renders the typed sub-structures.
//
// Each is produced from a domain type and consumed by the same type. The JSON
// is never interpreted, never templated, and never returned to a caller as
// text.
func encodeUpdatePolicyDocuments(policy domain.UpdatePolicy) (updatePolicyDocuments, error) {
	selector, err := json.Marshal(policy.Selector)
	if err != nil {
		return updatePolicyDocuments{}, fmt.Errorf("encode update policy selector: %w", err)
	}
	window, err := json.Marshal(policy.Window)
	if err != nil {
		return updatePolicyDocuments{}, fmt.Errorf("encode update policy window: %w", err)
	}
	limits, err := json.Marshal(policy.Limits)
	if err != nil {
		return updatePolicyDocuments{}, fmt.Errorf("encode update policy limits: %w", err)
	}
	failure, err := json.Marshal(policy.Failure)
	if err != nil {
		return updatePolicyDocuments{}, fmt.Errorf("encode update policy failure handling: %w", err)
	}
	return updatePolicyDocuments{
		selector: string(selector),
		window:   string(window),
		limits:   string(limits),
		failure:  string(failure),
	}, nil
}

func scanUpdatePolicyRow(row *sql.Row) (domain.UpdatePolicy, error) {
	policy, err := scanUpdatePolicy(row)
	if errors.Is(err, sql.ErrNoRows) {
		return domain.UpdatePolicy{}, ErrNotFound
	}
	return policy, err
}

func scanUpdatePolicy(scanner rowScanner) (domain.UpdatePolicy, error) {
	var (
		policy                                     domain.UpdatePolicy
		enabled, archived                          int
		selector, windowDoc, limitsDoc, failureDoc string
	)
	err := scanner.Scan(
		&policy.ID, &policy.PolicyID, &policy.Name, &policy.Description,
		&enabled, &archived, &policy.Priority,
		&policy.Scope, &policy.Strategy, &policy.Mode, &policy.MinimumRecommendation,
		&selector, &windowDoc, &limitsDoc, &failureDoc,
		&policy.CreatedAt, &policy.UpdatedAt)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return domain.UpdatePolicy{}, err
		}
		return domain.UpdatePolicy{}, fmt.Errorf("scan update policy: %w", AsError(err))
	}
	policy.Enabled = enabled == 1
	policy.Archived = archived == 1

	// A row this build cannot decode is refused rather than served with an
	// empty selector, which would be a policy that governs nothing while
	// claiming to govern something.
	if err := json.Unmarshal([]byte(selector), &policy.Selector); err != nil {
		return domain.UpdatePolicy{}, fmt.Errorf("decode update policy %s selector: %w", policy.PolicyID, err)
	}
	if err := json.Unmarshal([]byte(windowDoc), &policy.Window); err != nil {
		return domain.UpdatePolicy{}, fmt.Errorf("decode update policy %s window: %w", policy.PolicyID, err)
	}
	if err := json.Unmarshal([]byte(limitsDoc), &policy.Limits); err != nil {
		return domain.UpdatePolicy{}, fmt.Errorf("decode update policy %s limits: %w", policy.PolicyID, err)
	}
	if err := json.Unmarshal([]byte(failureDoc), &policy.Failure); err != nil {
		return domain.UpdatePolicy{}, fmt.Errorf("decode update policy %s failure handling: %w", policy.PolicyID, err)
	}
	return policy, nil
}

func (r *UpdatePolicyRepository) nameTaken(ctx context.Context, name, excluding string) (bool, error) {
	var count int
	err := r.db.QueryRowContext(ctx, `
		SELECT COUNT(*) FROM update_policies
		 WHERE archived = 0 AND name = ? AND policy_id <> ?`,
		name, excluding).Scan(&count)
	if err != nil {
		return false, fmt.Errorf("check update policy name: %w", AsError(err))
	}
	return count > 0, nil
}

// txUpdatePolicyNameTaken is nameTaken inside an open transaction.
func txUpdatePolicyNameTaken(ctx context.Context, tx *sql.Tx, name, excluding string) (bool, error) {
	var count int
	err := tx.QueryRowContext(ctx, `
		SELECT COUNT(*) FROM update_policies
		 WHERE archived = 0 AND name = ? AND policy_id <> ?`,
		name, excluding).Scan(&count)
	if err != nil {
		return false, fmt.Errorf("check update policy name: %w", AsError(err))
	}
	return count > 0, nil
}

// sortStrings sorts in place. A local helper so this file does not pull `sort`
// in for one call.
func sortStrings(values []string) {
	for i := 1; i < len(values); i++ {
		for j := i; j > 0 && values[j] < values[j-1]; j-- {
			values[j], values[j-1] = values[j-1], values[j]
		}
	}
}
