package domain

import "strconv"

// Manual recovery plans.
//
// # Why this exists
//
// HarborMaster does not roll back. A recreation that fails after the mutation
// point leaves two containers on the host -- the parked original and the
// quarantined replacement -- and stops. That is deliberate: an automatic undo
// is another unattended mutation, performed at exactly the moment HarborMaster
// has just demonstrated that its model of the host is wrong.
//
// But "we stopped and left it to you" is only acceptable if HarborMaster is
// precise about what it left. A recovery plan is that precision: the exact
// state of the host, the exact container names and ids, and the exact commands
// that would restore service.
//
// # It is text, and only text
//
// Nothing executes a recovery plan. There is no endpoint that runs one, no
// button that applies one, and no capability behind either. Every step is
// assembled here from a FIXED vocabulary and values HarborMaster generated or
// read from the daemon -- never from caller input, never from a daemon error
// string.
//
// The commands are shown so an operator can read them, understand them, and
// decide. They are rendered for display; HarborMaster never shells out.

// RecoveryUrgency ranks how much a situation needs attention.
type RecoveryUrgency string

// Recovery urgencies.
const (
	// RecoveryInformational means nothing on the host needs settling. The
	// recreation failed before it changed anything.
	RecoveryInformational RecoveryUrgency = "informational"
	// RecoveryAttention means containers were left behind that an operator
	// should tidy up, but the service the container provides is running.
	RecoveryAttention RecoveryUrgency = "attention"
	// RecoveryUrgent means the container is NOT SERVING. Something is stopped
	// that an operator expects to be running.
	RecoveryUrgent RecoveryUrgency = "urgent"
)

// RecoveryStep is one instruction in a recovery plan.
type RecoveryStep struct {
	// Order is the step's position, one-based.
	Order int `json:"order"`
	// Description is HarborMaster's own sentence about what this step does and
	// why. Never a daemon string.
	Description string `json:"description"`
	// Command is the command an operator would run. Rendered for reading;
	// HarborMaster never executes it.
	Command string `json:"command,omitempty"`
	// Destructive marks a step that removes something. Called out so an
	// operator reading quickly does not run one by reflex.
	Destructive bool `json:"destructive"`
}

// RecoveryPlan describes the host after a failed recreation, and what to do.
type RecoveryPlan struct {
	Urgency RecoveryUrgency `json:"urgency"`
	// Situation is a plain statement of what is true of the host right now.
	Situation string `json:"situation"`
	// Steps are the recommended actions, in order.
	Steps []RecoveryStep `json:"steps"`
	// ServiceInterrupted reports whether the container is currently not
	// serving. The single most important fact on this record.
	ServiceInterrupted bool `json:"serviceInterrupted"`
}

// MaxRecoverySteps bounds a plan. Every plan this file builds is well under
// it; the bound exists so a future edit cannot produce an unbounded document
// in a column an API returns.
const MaxRecoverySteps = 12

// RecoveryContext is what a plan is built from.
//
// Every field is either generated by HarborMaster or read from the daemon
// through the normalising adapter. None of it is caller input.
type RecoveryContext struct {
	ExecutionID string
	// ContainerName is the name the container is expected to answer to.
	ContainerName string
	// OriginalID is the original container, and ParkedName the name it was
	// renamed to. ParkedName is empty when the rename never happened.
	OriginalID string
	ParkedName string
	// ReplacementID is the container that was created, and QuarantineName the
	// name it was renamed to. Both empty when no replacement exists.
	ReplacementID  string
	QuarantineName string

	Checkpoint ExecutionCheckpoint
	Failure    ExecutionFailure

	// MutationAttempted reports that a mutation was ISSUED, whether or not any
	// checkpoint confirmed it.
	//
	// The distinction this field exists for is the one a naive design gets
	// wrong. A checkpoint of none normally means "nothing was changed", and
	// saying so is the most useful thing a plan can do. But a process killed
	// between issuing a stop and recording it also has a checkpoint of none --
	// and telling that operator "nothing was changed" would be a confident,
	// specific, and false statement about a container that may well be down.
	MutationAttempted bool
}

// BuildRecoveryPlan describes the host and recommends manual steps.
//
// The plan is driven by the CHECKPOINT rather than by the failure, because the
// checkpoint is what says what is true of the host. The failure decides the
// wording of the diagnosis; the checkpoint decides the actions.
func BuildRecoveryPlan(context RecoveryContext) *RecoveryPlan {
	switch context.Checkpoint {
	case CheckpointNone:
		if !context.MutationAttempted {
			// Nothing was changed. There is nothing to recover, and saying so
			// explicitly is more useful than omitting the plan and leaving an
			// operator to wonder.
			return &RecoveryPlan{
				Urgency: RecoveryInformational,
				Situation: "Nothing on this host was changed. The recreation stopped before it " +
					"touched anything, so the container is exactly as it was.",
			}
		}
		// A stop was issued and never confirmed. HarborMaster does not know
		// whether it landed, and the plan says so rather than guessing --
		// guessing "stopped" would send an operator to restart something that
		// is already running, and guessing "running" would leave a container
		// down with a record claiming otherwise.
		//
		// Falls through to the shared tail below, which appends the container
		// identities and numbers every step.

	case CheckpointOriginalRemoved:
		// The success path reached its end. A plan here means something went
		// wrong recording it, not something wrong with the host.
		return &RecoveryPlan{
			Urgency: RecoveryInformational,
			Situation: "The recreation completed on this host: the replacement is running under " +
				"its own name and the original has been removed. Only HarborMaster's own record " +
				"of the outcome is in doubt.",
		}
	}

	name := context.ContainerName
	if name == "" {
		name = "the container"
	}

	plan := &RecoveryPlan{}
	if context.Checkpoint == CheckpointNone {
		// The uncertain case: reached only when a mutation was attempted, since
		// the switch above returned for the ordinary one.
		plan = uncertainStopPlan(name)
	}

	switch context.Checkpoint {
	case CheckpointOriginalStopped:
		// The original is stopped under its own name and nothing was created.
		// The simplest situation to recover from, and the most urgent: the
		// service is down and one command brings it back.
		plan.Urgency = RecoveryUrgent
		plan.ServiceInterrupted = true
		plan.Situation = "The original container was stopped and nothing was created. It still " +
			"carries its own name, so starting it restores service exactly as it was."
		plan.Steps = []RecoveryStep{
			{Description: "Start the original container again. It is unchanged and still on its original image.",
				Command: "docker start " + shellName(name)},
		}

	case CheckpointOriginalParked:
		plan.Urgency = RecoveryUrgent
		plan.ServiceInterrupted = true
		plan.Situation = "The original container was stopped and renamed aside, and no replacement " +
			"was created. Nothing answers to " + name + " right now."
		plan.Steps = []RecoveryStep{
			{Description: "Give the original its name back.",
				Command: "docker rename " + shellName(context.ParkedName) + " " + shellName(name)},
			{Description: "Start it. It is unchanged and still on its original image.",
				Command: "docker start " + shellName(name)},
		}

	case CheckpointReplacementCreated, CheckpointReplacementStarted, CheckpointReplacementQuarantined:
		plan.Urgency = RecoveryUrgent
		plan.ServiceInterrupted = true
		plan.Situation = "Both containers are on this host and neither is serving. The replacement " +
			"was created on the new image and did not pass verification; the original is stopped, " +
			"unchanged, and preserved. Nothing has been removed."

		replacement := context.QuarantineName
		if replacement == "" {
			replacement = context.ReplacementID
		}

		plan.Steps = []RecoveryStep{
			{Description: "Look at why the replacement did not work. Its logs are the most direct evidence, " +
				"and it has been kept precisely so you can read them.",
				Command: "docker logs " + shellName(replacement)},
			{Description: "To restore service on the ORIGINAL image, give the original its name back and start it.",
				Command: "docker rename " + shellName(context.ParkedName) + " " + shellName(name)},
			{Description: "Start the original. It is unchanged.",
				Command: "docker start " + shellName(name)},
			{Description: "Once you no longer need it as evidence, remove the failed replacement.",
				Command:     "docker rm " + shellName(replacement),
				Destructive: true},
		}

	case CheckpointReplacementVerified:
		// Everything passed but the outcome could not be recorded. The
		// replacement IS serving, so this is tidying rather than an outage.
		plan.Urgency = RecoveryAttention
		plan.ServiceInterrupted = false
		plan.Situation = "The replacement passed every verification and is running under its own " +
			"name, so the service is up on the new image. HarborMaster could not confirm its own " +
			"record of that, so it left the original in place rather than removing it."
		plan.Steps = []RecoveryStep{
			{Description: "Confirm the replacement is the container you expect, and is healthy.",
				Command: "docker inspect " + shellName(name)},
			{Description: "Once you are satisfied, remove the parked original. Nothing needs it any more.",
				Command:     "docker rm " + shellName(context.ParkedName),
				Destructive: true},
		}

	case CheckpointNone:
		// The uncertain-stop plan, already built above. Named explicitly rather
		// than left to the default, which would overwrite it with the weaker
		// "we do not know" wording and lose the one useful thing this case can
		// say: exactly which question the operator needs to answer.

	default:
		// An unrecognised checkpoint is a gap in HarborMaster's own model, and
		// the honest response is to say so rather than to recommend an action
		// derived from an assumption.
		plan.Urgency = RecoveryAttention
		plan.Situation = "HarborMaster is not certain what state this host was left in. Inspect the " +
			"containers below before acting."
	}

	// The identities, appended last so they are present on every plan including
	// the uncertain one. An operator whose names have been reorganised needs
	// ids, which do not change.
	plan.Steps = append(plan.Steps, identitySteps(context, len(plan.Steps))...)

	if len(plan.Steps) > MaxRecoverySteps {
		plan.Steps = plan.Steps[:MaxRecoverySteps]
	}
	for i := range plan.Steps {
		plan.Steps[i].Order = i + 1
	}
	return plan
}

// uncertainStopPlan describes a stop that was issued and never confirmed.
//
// The honest plan. Every step begins by having the operator LOOK, because
// HarborMaster genuinely does not know the answer and a plan that pretended
// otherwise would be worse than no plan at all.
//
// Urgency is urgent rather than attention: if the stop did land, a container is
// down and nobody has been told.
func uncertainStopPlan(name string) *RecoveryPlan {
	return &RecoveryPlan{
		Urgency:            RecoveryUrgent,
		ServiceInterrupted: true,
		Situation: "HarborMaster asked for the original container to be stopped and was " +
			"interrupted before it could confirm the result. It does not know whether the " +
			"container is running. No replacement was created, and nothing was renamed or " +
			"removed.",
		Steps: []RecoveryStep{
			{Description: "Check whether the container is running. This is the question " +
				"HarborMaster could not answer for itself.",
				Command: "docker inspect --format '{{.State.Status}}' " + shellName(name)},
			{Description: "If it is stopped, start it. It is unchanged and still on its original image.",
				Command: "docker start " + shellName(name)},
			{Description: "If it is running, nothing needs doing: the stop did not take effect."},
		},
	}
}

// identitySteps appends the container identities as inspectable facts.
//
// Ids rather than names, because a failure during a rename is precisely the
// case where the names are not what anyone expects.
func identitySteps(context RecoveryContext, offset int) []RecoveryStep {
	steps := make([]RecoveryStep, 0, 2)

	if context.OriginalID != "" {
		steps = append(steps, RecoveryStep{
			Order: offset + len(steps) + 1,
			Description: "The original container's id is " + ShortenID(context.OriginalID) +
				". Names can be reorganised; this cannot.",
			Command: "docker inspect " + ShortenID(context.OriginalID),
		})
	}
	if context.ReplacementID != "" {
		steps = append(steps, RecoveryStep{
			Order:       offset + len(steps) + 1,
			Description: "The replacement container's id is " + ShortenID(context.ReplacementID) + ".",
			Command:     "docker inspect " + ShortenID(context.ReplacementID),
		})
	}
	return steps
}

// shellName renders a container name for a command an operator reads.
//
// # This is not shell escaping, and must not be mistaken for it
//
// HarborMaster never executes these commands. There is no shell, no exec, and
// no capability to add one -- so there is nothing here to inject into. The
// quoting exists so that a name containing an unusual character is READABLE and
// copy-pasteable, not because the value is untrusted at this point.
//
// The value is trusted at this point, twice over: every name in a recovery plan
// was either generated by HarborMaster from its own entropy source or read from
// the daemon and validated by ValidContainerName, whose allowlist admits only
// alphanumerics, underscore, dot, and dash. A name needing quotes should be
// impossible; it is quoted anyway, because "should be impossible" is not a
// property worth relying on in text an operator may paste into a terminal.
func shellName(name string) string {
	if name == "" {
		return "<unknown>"
	}
	if ValidContainerName(name) {
		return name
	}
	// Not a name HarborMaster would have created. Rendered as a quoted literal
	// so it is unmistakably one argument, and bounded so it cannot dominate the
	// plan.
	return strconv.Quote(SanitiseDisplayText(name, MaxContainerNameBytes))
}
