/// <reference types="vitest/config" />
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { defineConfig, type Plugin } from "vite";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

// The dev server proxies /api to the Go backend so the frontend uses the same
// relative URLs in development as it does when served from the embedded bundle.
const BACKEND_ORIGIN = process.env.HARBORMASTER_DEV_BACKEND ?? "http://127.0.0.1:8080";

const GITKEEP_NOTE = `This directory holds the compiled frontend bundle, which web/embed.go embeds
into the Go binary. Build output is generated by \`make web-build\` and is not
committed; this placeholder exists so \`go:embed all:dist\` has something to match
and the backend builds on a clean checkout.

It is rewritten after every build by the keepDistPlaceholder plugin in
vite.config.ts, because \`emptyOutDir\` would otherwise delete it.
`;

/**
 * Restores dist/.gitkeep after each build.
 *
 * `go:embed all:dist` fails to compile when the directory has no files, so a
 * committed placeholder is what lets the backend build without the frontend.
 * `emptyOutDir` wipes it, so it has to be put back.
 */
function keepDistPlaceholder(): Plugin {
  return {
    name: "harbormaster:keep-dist-placeholder",
    apply: "build",
    closeBundle: {
      order: "post",
      handler() {
        writeFileSync(
          resolve(import.meta.dirname, "dist", ".gitkeep"),
          GITKEEP_NOTE,
          "utf8",
        );
      },
    },
  };
}

export default defineConfig({
  plugins: [react(), tailwindcss(), keepDistPlaceholder()],
  server: {
    port: 5173,
    // Loopback only: the dev server fronts an API that talks to the Docker socket.
    host: "127.0.0.1",
    proxy: {
      "/api": {
        target: BACKEND_ORIGIN,
        changeOrigin: false,
      },
    },
  },
  build: {
    // Consumed by web/embed.go via go:embed.
    outDir: "dist",
    emptyOutDir: true,
    sourcemap: false,
  },
  test: {
    environment: "jsdom",
    globals: true,
    setupFiles: ["./src/test/setup.ts"],
    css: false,
    include: ["src/**/*.test.{ts,tsx}"],
  },
});
